[phases.setup]
nixPkgs = ["nodejs_23", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "cd packages/cli && bun start --character=../../characters/kairos.json"
