[phases.setup]
nixPkgs = ["nodejs_23", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["npx turbo run build --filter=!./packages/app --filter=!@elizaos/config --concurrency=2"]

[start]
cmd = "cd packages/cli && bun start --character=../../characters/kairos.json"
